;;; ps-info-triage.el --- Work the info-triage inbox from Emacs -*- lexical-binding: t; -*-

;;; Commentary:
;; The daily loop for the separate `info-triage' project (checked out at
;; ~/projects/tools/info-triage): material forwarded to Telegram is extracted on
;; a NAS, `sync.sh' pulls it to ~/info-triage-inbox/ as one directory per item,
;; and two generated views describe them -- `triage.md' for the routing agent
;; and `triage.org' for the person.  This module is the person's half: sync,
;; read the queue, follow an item into its artifacts, drop what is not worth
;; keeping, and repeat.
;;
;; Three things here are load-bearing.
;;
;; The queue is READ-ONLY, and not out of caution: `triage.org' is regenerated
;; wholesale on every sync, so anything typed into it is lost.  Making that
;; explicit also frees the single-key bindings below, which is what makes the
;; buffer feel like Dired rather than like a file that must not be touched.
;;
;; The item's directory is parsed back out of its `directory' link.  That link
;; is the only place the id appears now that the property drawer is gone (see
;; `render_org' in the project's info_triage/sync.py), so its shape is a
;; contract between the two repositories and `ps/info-triage--item-directory'
;; is the one place this side depends on it.  The queue's outline shape is part
;; of the same contract: a level-one heading per day, items under it at level
;; two, and the number in an item's heading global across the days.
;;
;; Dropping an item regenerates BOTH views before reverting.  `triage.md' and
;; `triage.org' number their items positionally and independently, and the whole
;; interface between the two halves is that the numbers agree: the user reads a
;; number here and quotes it to an agent that reads the other file.  Removing a
;; directory renumbers everything after it, so the views must be rebuilt
;; together -- which is what `sync.sh --regenerate' exists for.

;;; Code:

(require 'seq)
;; A real require, not a declaration: the keymap below is built at load time
;; and `ps/open-bind-click' has to exist by then.
(require 'ps-open)

(declare-function ps/window-replace-here "ps-window")
(declare-function ps/window-visit-here "ps-window")
(declare-function ps/window--select-main "ps-window")
(declare-function ps/nav-back "ps-nav")
(declare-function ps/nav-forward "ps-nav")
(declare-function org-back-to-heading "org")
(declare-function org-open-at-point "org")
(declare-function org-link-display-format "ol")
(declare-function org-element-context "org-element")
(declare-function org-element-lineage "org-element-ast")
(declare-function org-element-property "org-element-ast")

(defgroup ps/info-triage nil
  "Review the info-triage capture inbox."
  :group 'ps)

(defcustom ps/info-triage-directory (expand-file-name "~/info-triage-inbox/info/")
  "Directory holding the capture queue this feature works.

The sync script pulls each of its routes into its own subdirectory of
~/info-triage-inbox/, and each is a self-contained queue: its own items, its
own `triage.org' beside them, its own numbering from 1.  This points at the
default route, which is the only one triaged by hand -- job, clip and lang are
consumed by scripts.  Point it at another route's directory to work that one
instead; nothing else here needs to change, because an item's `directory' link
is relative to the queue that lists it.

Everything in this feature is hidden when it does not exist, so a machine
without the info-triage project never sees a menu for it."
  :type 'directory
  :group 'ps/info-triage)

(defcustom ps/info-triage-sync-script
  (expand-file-name "~/projects/tools/info-triage/sync.sh")
  "The info-triage synchronization script."
  :type 'file
  :group 'ps/info-triage)

(defcustom ps/info-triage-open-beside t
  "Whether an item opens beside the queue rather than in its window.

With this on -- the default -- the queue keeps its window for good: the first
item you open splits and takes the other pane, and every item after that lands
in that same pane.  The list is read down over and over, so an item opening
into it would take the list away every time.

Turn it off for one window at a time: the item replaces the queue and `‹'
brings it back."
  :type 'boolean
  :group 'ps/info-triage)

(defcustom ps/info-triage-external-command "code"
  "Program that opens an item's directory outside Emacs.
The escape hatch for a mixed-media item Emacs is the wrong tool for."
  :type 'string
  :group 'ps/info-triage)

(defconst ps/info-triage-queue-name "triage.org"
  "The generated navigation view, inside `ps/info-triage-directory'.")

(defconst ps/info-triage--directory-link-re
  "\\[\\[file:\\([^]/]+\\)/\\]\\[directory\\]\\]"
  "Matches the queue's `directory' link, capturing the item's directory name.
Generated by `render_org' in the info-triage project; the only place an
item's id still appears.")

(defconst ps/info-triage--heading-re "^\\*\\* \\([0-9]+\\) "
  "Matches a queue item's heading, capturing the item number.
Level two: the queue groups its items under a level-one heading per day.  The
number is still global across the days -- it is what a routing agent is quoted
and it has to keep meaning the same item in both views.")

(defconst ps/info-triage--any-heading-re "^\\*+ "
  "Matches any queue heading, an item's or a day's.
Used to bound a search inside one item: the *next* heading may be the day
after this one rather than another item.")

;;; Where things are

(defun ps/info-triage-queue-file ()
  "Return the path of the generated queue."
  (expand-file-name ps/info-triage-queue-name ps/info-triage-directory))

;;;###autoload
(defun ps/info-triage-available-p ()
  "Non-nil when this machine has an info-triage inbox to work with."
  (file-directory-p ps/info-triage-directory))

(defun ps/info-triage-queue-buffer-p (&optional buffer)
  "Non-nil when BUFFER (default current) is visiting the generated queue."
  (with-current-buffer (or buffer (current-buffer))
    (and buffer-file-name
         (equal (file-truename buffer-file-name)
                (file-truename (ps/info-triage-queue-file))))))

;;; Reading the item at point

(defun ps/info-triage--item-directory ()
  "Return the directory name of the item at point, or nil.

Read out of the heading's `directory' link rather than a property, because
the queue no longer carries a drawer -- see this file's Commentary."
  (save-excursion
    (when (ignore-errors (org-back-to-heading t) t)
      ;; Bounded by the NEXT heading of any level, searched for from the line
      ;; below this one -- from the heading itself the search matches this
      ;; heading and the bound collapses to nothing, which reads as an item with
      ;; no links at all.  Any level, because the last item of a day is followed
      ;; by the next day rather than by another item.
      (let ((end (save-excursion
                   (forward-line 1)
                   (if (re-search-forward ps/info-triage--any-heading-re nil t)
                       (match-beginning 0)
                     (point-max)))))
        (when (re-search-forward ps/info-triage--directory-link-re end t)
          (match-string-no-properties 1))))))

(defun ps/info-triage--item-number ()
  "Return the number of the item at point as a string, or nil."
  (save-excursion
    (when (ignore-errors (org-back-to-heading t) t)
      (when (looking-at ps/info-triage--heading-re)
        (match-string-no-properties 1)))))

(defun ps/info-triage--item-path ()
  "Return the absolute path of the item at point, or signal."
  (let ((name (or (ps/info-triage--item-directory)
                  (user-error "Point is not on an item"))))
    (expand-file-name name ps/info-triage-directory)))

(defun ps/info-triage--item-label ()
  "Return the item at point's heading without what the prompt already says.
The number is repeated by the caller, and the kind tag is Org markup rather
than something to read back at someone.  The title is a link to the item's
index, so it is reduced to the text that is actually on screen."
  (save-excursion
    (org-back-to-heading t)
    (let ((heading (buffer-substring-no-properties (pos-bol) (pos-eol))))
      (string-trim
       (org-link-display-format
        (replace-regexp-in-string
         "\\s-+:[[:alnum:]_@#%:]+:\\s-*\\'" ""
         (replace-regexp-in-string "\\`\\*+ +[0-9]+ · " "" heading)))))))

(defun ps/info-triage--item-size (path)
  "Return a short description of what PATH holds, for a confirmation prompt."
  (let ((files (and (file-directory-p path)
                    (directory-files-recursively path "" nil))))
    (format "%d file%s" (length files) (if (= (length files) 1) "" "s"))))

;;; Commands

;;;###autoload
(defun ps/info-triage-open ()
  "Open the capture queue in this window."
  (interactive)
  (unless (ps/info-triage-available-p)
    (user-error "No info-triage inbox at %s" ps/info-triage-directory))
  (let ((file (ps/info-triage-queue-file)))
    (unless (file-exists-p file)
      (user-error "No %s yet -- synchronize first" ps/info-triage-queue-name))
    (ps/window-visit-here file)))

(defun ps/info-triage--revert-queue ()
  "Reload the queue buffer if it is open, keeping the item you were reading.

The file is regenerated wholesale and carries no state, so reverting can
never lose anything: removing an item's directory is the only signal that it
was processed."
  (when-let* ((buffer (find-buffer-visiting (ps/info-triage-queue-file))))
    (with-current-buffer buffer
      (let ((number (ps/info-triage--item-number))
            (inhibit-read-only t))
        (revert-buffer :ignore-auto :noconfirm)
        ;; Numbers shift when an item is dropped, so this lands on whatever now
        ;; holds that position -- which is the next item, and is what you want.
        (when number
          (goto-char (point-min))
          (re-search-forward (format "^\\*\\* %s " (regexp-quote number)) nil t)
          (beginning-of-line))))))

(defun ps/info-triage--run (arguments on-success)
  "Run the sync script with ARGUMENTS, then call ON-SUCCESS.
Asynchronous and quiet: the output buffer is only shown when the script
fails, so a routine sync does not take a window away from what you were
reading."
  (unless (file-executable-p ps/info-triage-sync-script)
    (user-error "Not executable: %s" ps/info-triage-sync-script))
  (let ((output (get-buffer-create "*info-triage sync*")))
    (with-current-buffer output
      (let ((inhibit-read-only t)) (erase-buffer)))
    (message "Info Triage: %s…" (if arguments "regenerating" "synchronizing"))
    (make-process
     :name "ps-info-triage-sync"
     :buffer output
     :noquery t
     ;; Through a login shell, not directly: the script runs `uv', and a
     ;; Finder-launched Emacs inherits a PATH that does not have it.
     :command (list shell-file-name "-lc"
                    (mapconcat #'shell-quote-argument
                               (cons ps/info-triage-sync-script arguments) " "))
     :sentinel
     (lambda (process _event)
       (when (memq (process-status process) '(exit signal))
         (if (zerop (process-exit-status process))
             (progn (funcall on-success)
                    (message "Info Triage: done"))
           (display-buffer output)
           (message "Info Triage: %s failed -- see *info-triage sync*"
                    ps/info-triage-sync-script)))))))

;;;###autoload
(defun ps/info-triage-sync ()
  "Fetch new captures from the NAS and propagate anything dropped here."
  (interactive)
  (ps/info-triage--run nil #'ps/info-triage--revert-queue))

;;;###autoload
(defun ps/info-triage-regenerate ()
  "Rebuild both views from the item directories present, without the network.
Both are renumbered together, which is what keeps the number shown here and
the number a routing agent reads naming the same item."
  (interactive)
  (ps/info-triage--run '("--regenerate") #'ps/info-triage--revert-queue))

;;;###autoload
(defun ps/info-triage-drop ()
  "Drop the item at point: move its directory to the Trash and renumber.

Deleting the directory is the project's own signal that an item was
processed, so the next synchronization removes the NAS copy too.  It goes to
the Trash rather than being unlinked because the decision is a judgement made
at a glance, and a glance is sometimes wrong."
  (interactive)
  (let* ((path (ps/info-triage--item-path))
         (number (ps/info-triage--item-number))
         (label (ps/info-triage--item-label)))
    (unless (file-directory-p path)
      (user-error "No such item directory: %s" path))
    (when (yes-or-no-p (format "Drop item %s (%s) — %s? "
                               (or number "?")
                               (ps/info-triage--item-size path)
                               label))
      (let ((delete-by-moving-to-trash t))
        (delete-directory path :recursive :trash))
      (ps/info-triage-regenerate))))

;;;###autoload
(defun ps/info-triage-open-externally ()
  "Open the item at point's directory outside Emacs.
The escape hatch: an item whose payload is twenty images and a video is one
a file browser shows better than this does."
  (interactive)
  (let ((path (if (ps/info-triage-queue-buffer-p)
                  (ps/info-triage--item-path)
                (expand-file-name ps/info-triage-directory))))
    (let ((program (executable-find ps/info-triage-external-command)))
      (unless program
        (user-error "No `%s' on PATH" ps/info-triage-external-command))
      (call-process program nil 0 nil path)
      (message "Opened %s outside Emacs" (abbreviate-file-name path)))))

(defun ps/info-triage--move-item (count)
  "Move point COUNT items forward, or backward when COUNT is negative.
Returns non-nil when it moved.  Days are headings too, so stepping with
`org-next-visible-heading' would stop on a date -- a stop where none of the
single keys mean anything."
  (let ((start (point))
        (search (if (> count 0) #'re-search-forward #'re-search-backward)))
    (when (> count 0) (end-of-line))
    (when (< count 0) (beginning-of-line))
    (if (funcall search ps/info-triage--heading-re nil t (abs count))
        (progn (beginning-of-line) t)
      (goto-char start)
      nil)))

;;;###autoload
(defun ps/info-triage-next-item ()
  "Move to the next item in the queue."
  (interactive)
  (unless (ps/info-triage--move-item 1)
    (message "Last item")))

;;;###autoload
(defun ps/info-triage-previous-item ()
  "Move to the previous item in the queue."
  (interactive)
  (unless (ps/info-triage--move-item -1)
    (message "First item")))

(defun ps/info-triage-follow ()
  "Follow the link at point, or open the item's index when point is not on one.

Bound over `org-open-at-point' rather than replacing Org's file handling,
because the whole point is that a `.md' link renders, a `.pdf' link goes to
Preview and a `.mp4' link goes to the system player -- which is
`ps/open-file's job, and Org would visit all three as text."
  (interactive)
  (let ((link (org-element-lineage (org-element-context) '(link) t)))
    (if (null link)
        (ps/open-file (expand-file-name "index.md" (ps/info-triage--item-path)))
      (let ((type (org-element-property :type link))
            (path (org-element-property :path link)))
        (cond
         ((equal type "file") (ps/open-file (expand-file-name path default-directory)))
         ((member type '("http" "https")) (browse-url (format "%s:%s" type path)))
         (t (org-open-at-point)))))))

(defun ps/info-triage-follow-at-mouse (event)
  "Follow whatever EVENT clicked on.
Point is normally already at the click by the time a mouse-2 binding runs, but
a middle click arrives with no preceding drag -- which is why the command this
replaces, `org-open-at-mouse', sets point itself."
  (interactive "e")
  (mouse-set-point event)
  (ps/info-triage-follow))

;;; The queue buffer

(defvar ps/info-triage-mode-map
  (let ((map (make-sparse-keymap)))
    ;; A remap rather than a key: Org puts its own keymap on a link as a text
    ;; property, which outranks a minor-mode map, so binding RET and mouse-1
    ;; alone would leave clicking a link going somewhere else entirely.
    ;;
    ;; BOTH remaps are needed, and the second is the one that was missing.
    ;; `org-mouse-map' binds mouse-2 to `org-open-at-mouse', a *separate*
    ;; command that ends in a plain `(org-open-at-point)' function call --
    ;; and remapping rewrites command dispatch, never a funcall.  So with only
    ;; the first line here, every mouse click went through stock Org file
    ;; handling and opened the item in another window.
    (define-key map [remap org-open-at-point] #'ps/info-triage-follow)
    (define-key map [remap org-open-at-mouse] #'ps/info-triage-follow-at-mouse)
    ;; And the mouse directly, because even that pair is not enough: a click
    ;; that reaches Org at all has already moved point into the link, which
    ;; `org-appear' answers by revealing its raw syntax -- the line grows under
    ;; the pointer and the release lands somewhere else.  `ps/open-bind-click'
    ;; follows on the *press* and never moves point.  See `ps/open-down-click'.
    (ps/open-bind-click map)
    (define-key map (kbd "RET") #'ps/info-triage-follow)
    (define-key map (kbd "n")   #'ps/info-triage-next-item)
    (define-key map (kbd "p")   #'ps/info-triage-previous-item)
    (define-key map (kbd "d")   #'ps/info-triage-drop)
    (define-key map (kbd "s")   #'ps/info-triage-sync)
    (define-key map (kbd "g")   #'ps/info-triage-regenerate)
    (define-key map (kbd "e")   #'ps/info-triage-open-externally)
    (define-key map (kbd "b")   #'ps/nav-back)
    (define-key map (kbd "f")   #'ps/nav-forward)
    (define-key map (kbd "q")   #'bury-buffer)
    map)
  "Keymap for `ps/info-triage-mode'.
Single keys, Dired-style, which the buffer being read-only is what allows.")

(define-minor-mode ps/info-triage-mode
  "Minor mode for the generated info-triage queue.

The buffer is read-only because it is regenerated on every sync: anything
typed here is lost, and saying so up front is also what frees the single-key
bindings."
  :lighter " Triage"
  :keymap ps/info-triage-mode-map
  (setq buffer-read-only (and ps/info-triage-mode t))
  ;; A click here follows a link and nothing else -- the RET behaviour of
  ;; opening the item at point when there is no link would mean clicking
  ;; anywhere at all opened something.
  (if ps/info-triage-mode
      (ps/open-setup-click #'ps/info-triage-follow)
    (setq-local ps/open-follow-function nil))
  ;; The queue stays where it is and items open beside it; see
  ;; `ps/info-triage-open-beside'.
  (setq-local ps/open-keep-window
              (and ps/info-triage-mode ps/info-triage-open-beside))
  ;; Org buffers get a line-number gutter here because plan files are worth
  ;; citing by line.  A generated queue is not: its items are addressed by the
  ;; number printed in each heading, and a second, different set of numbers
  ;; running down the left margin is the one thing guaranteed to be misread.
  (display-line-numbers-mode (if ps/info-triage-mode 0 1)))

(defun ps/info-triage--maybe-enable ()
  "Turn on `ps/info-triage-mode' when this buffer is the queue."
  (when (ps/info-triage-queue-buffer-p)
    (ps/info-triage-mode 1)))

;;;###autoload
(defun ps/info-triage-setup ()
  "Recognise the info-triage queue whenever it is opened."
  (add-hook 'org-mode-hook #'ps/info-triage--maybe-enable))

(provide 'ps-info-triage)
;;; ps-info-triage.el ends here
